"""empty message

Revision ID: 45d565bbc47b
Revises: 5df3dc8b4751
Create Date: 2018-06-13 17:15:38.878472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d565bbc47b'
down_revision = '5df3dc8b4751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('u_permission', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'u_permission')
    # ### end Alembic commands ###
