"""empty message

Revision ID: 5df3dc8b4751
Revises: deba79df2b04
Create Date: 2018-06-12 17:44:00.886190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df3dc8b4751'
down_revision = 'deba79df2b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_name', sa.String(length=16), nullable=True),
    sa.Column('u_email', sa.String(length=64), nullable=True),
    sa.Column('u_password', sa.String(length=256), nullable=True),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_email'),
    sa.UniqueConstraint('u_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
